name: flutter_app_icon_changer
description: "A new Flutter plugin project."
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_app_icon_changer
issue_tracker: https://github.com/Innim/flutter_app_icon_changer/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_app_icon_changer
        pluginClass: FlutterAppIconChangerPlugin
      ios:
        pluginClass: FlutterAppIconChangerPlugin
